services:
  nuxt-app:
    build: ./frontend
    container_name: nuxt-app
    restart: always
    ports:
      - "3000:3000"
    command: "yarn run start"
    networks:
      - nuxt-network
networks:
  nuxt-network:
    driver: bridge