services:
  nuxt-app:
    build: ./frontend
    container_name: nuxt-app
    restart: always
    ports:
      - "3000:3000"
    command: "yarn run start"
    networks:
      - nuxt-network
    depends_on:
      - django-app
    environment:
      - API_PARTY_CMS_URL=http://django-app:8000/api/v2

  db-postgis:
    image: postgis/postgis:16-3.4-alpine
    container_name: db-postgis
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
    volumes:
      - postgis-data:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - nuxt-network

  django-app:
  # TODO: debug the connection to the api app.
    build: 
      context: ./citizenvoice
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    container_name: django-app
    volumes:
      - ./citizenvoice:/citizenvoice
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_ENGINE=${DATABASE_ENGINE}
      - POSTGRES_DBASE=${POSTGRES_DBASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PWD=${POSTGRES_PWD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - db-postgis
    restart: unless-stopped
    networks:
      - nuxt-network

  web-server:
   build: 
    context: ./container/nginx
   container_name: web-server
   volumes:
     - ./container/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
     - web-root:/var/www/citizenvoice
   ports:
     - 80:80
   networks:
    - nuxt-network
   depends_on:
     - nuxt-app
     - django-app
   restart: unless-stopped

volumes:
  web-root:
  postgis-data:

networks:
  nuxt-network:
    driver: bridge