name: civo
services:

  postgis_db:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgis-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DATABASE}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_PASSWORD=/run/secrets/postgres_password
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DATABASE}
    restart: unless-stopped
    secrets:
      - postgres_password
    ports:
      - 5432:5432
    networks:
      - civo_network

  djangoapi:
    build: 
      context: ./citizenvoice
    command: >
      sh -c "python manage.py migrate &&
      python manage.py loaddata civilian-db.json &&
      python manage.py runserver 0.0.0.0:8000"
    container_name: django-api
    environment:
      - SECRET_KEY=/run/secrets/django_token
      - DATABASE_ENGINE=${DJANGO_DB_ENGINE}
      - POSTGRES_DBASE=${DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PWD=/run/secrets/postgres_password
      - POSTGRES_HOST=postgis_db
      - POSTGRES_PORT=${DB_PORT}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
    volumes:
      - ./citizenvoice:/citizenvoice
    ports:
      - "8000:8000"
    secrets:
      - django_token
      - postgres_password
    depends_on:
      postgis_db:
        condition: service_healthy
        restart: true
    networks:
      - civo_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 10s

  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    environment:
      - API_PARTY_CMS_URL=http://djangoapi:8000/voice/v3
      - AUTH_API_URL=http://djangoapi:8000/api/auth
      # - NODE_OPTIONS="--max-old-space-size=5120" # increases RAM for Node
    expose: # Expose ports without publishing them to the host machine
      - "3000"
    volumes:
      - ./frontend:/frontend
    depends_on:
      djangoapi:
        condition: service_healthy  
    restart: always
    networks:
      - civo_network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Read-only mounting of config
    depends_on:
      frontend:
        condition: service_started
      djangoapi:
        condition: service_healthy
    networks:
      - civo_network

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  django_token:
    file: ./secrets/django_token.txt
volumes:
  postgis_data:

networks:
  civo_network:
    driver: bridge
