services:
  nuxt-app:
    build: ./frontend
    container_name: nuxt-app
    restart: always
    ports:
      - "3000:3000"
    command: "yarn run start"
    networks:
      - nuxt-network

  db-postgis:
    image: postgis/postgis:16-3.4
    container_name: db-postgis
    volumes:
      - postgis-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
      POSTGRES_DB: ${POSTGRES_DBASE}
    ports:
      - "5432:5432"
    networks:
      - nuxt-network

  django-app:
    build: ./citizenvoice
    container_name: django-app
    volumes:
      - ./citizenvoice:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_ENGINE=${DATABASE_ENGINE}
      - POSTGRES_DBASE=${POSTGRES_DBASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PWD=${POSTGRES_PWD}
      - POSTGRES_HOST=db-postgis
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - db-postgis
    restart: unless-stopped
    networks:
      - nuxt-network
    command: python manage.py runserver

  web-server:
   image: nginx:1.27.1-alpine3.20
   container_name: web-server
   volumes:
     - ./container/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
     - web-root:/var/www/citizenvoice
   ports:
     - 80:80
   networks:
     nuxt-network:
   depends_on:
     - nuxt-app
   restart: unless-stopped

volumes:
  web-root:
  postgis-data:

networks:
  nuxt-network:
    driver: bridge