services:

  db_postgis:
    image: postgis/postgis:16-3.4-alpine
    container_name: db-postgis
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_PASSWORD=/run/secrets/postgres_password
    restart: unless-stopped
    secrets:
      - postgres_password
    ports:
      - 5432:5432
    networks:
      - civo-network

  django_app:
    build: 
      context: ./citizenvoice
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    container_name: django-app
    environment:
      - SECRET_KEY=/run/secrets/django_token
      - DATABASE_ENGINE=postgis
      - POSTGRES_DBASE=civo
      - POSTGRES_USER=citizen  # don't use quotes here
      - POSTGRES_PWD=/run/secrets/postgres_password
      - POSTGRES_HOST=db_postgis
      - POSTGRES_PORT=5432
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DJANGO_DEBUG=1
    volumes:
      - ./citizenvoice:/citizenvoice
    ports:
      - 8000:8000
    # env_file:
    #   - path: ./.env.dev
    #     required: true
    secrets:
      - django_token
      - postgres_password
    depends_on:
      - db_postgis
    # restart: unless-stopped
    networks:
      - civo-network



#   web_server:
#    build: 
#     context: ./container/nginx
#    container_name: web-server
#    volumes:
#      - ./container/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#      - web-root:/var/www/citizenvoice
#    ports:
#      - 8000:8000
#    networks:
#     - nuxt-network
#    depends_on:
#      - django-app
#    restart: unless-stopped

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  django_token:
    file: ./secrets/django_token.txt
volumes:
#   web_root:
  postgis_data:

networks:
  civo-network:
    driver: bridge