services:
  nuxt-app:
    build: ./frontend
    container_name: nuxt-app
    restart: always
    ports:
      - "3000:3000"
    command: "yarn run start"
    networks:
      - nuxt-network

  db-postgres:
    image: postgres:16.4
    container_name: db-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
      POSTGRES_DB: ${POSTGRES_DBASE}
    ports:
      - "5432:5432"
    networks:
      - nuxt-network

  web-server:
   image: nginx:1.27.1-alpine3.20
   container_name: web-server
   volumes:
     - ./container/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
     - web-root:/var/www/citizenvoice
   ports:
     - 80:80
   networks:
     nuxt-network:
   depends_on:
     - nuxt-app
   restart: unless-stopped

volumes:
  web-root:
  postgres-data:

networks:
  nuxt-network:
    driver: bridge