# Generated by Django 4.1.1 on 2023-05-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0010_alter_mapview_map_service_url_alter_mapview_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="response",
            name="interview_uuid",
        ),
    ]
